services:
  micro-mockba-binance-futures-bot:
    image: andresdom2004/micro-mockba-binance-futures-bot:latest
    container_name: micro-mockba-binance-futures-bot
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./llm_prompt_template.txt:/app/futures_perps/trade/binance/llm_prompt_template.txt
    depends_on:
      - redis-binance
    networks:
      - mockba-binance-net

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-binance
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_LIFECYCLE_HOOKS=true
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - mockba-binance-net

  redis-binance:
    image: redis:latest
    container_name: redis-mockba-binance
    restart: always
    ports:
      - "6392:6379"
    volumes:
      - redis_binance_data:/data
    networks:
      - mockba-binance-net

volumes:
  redis_binance_data:

networks:
  mockba-binance-net:
    driver: bridge